server:
  port: 8080

spring:
  application:
    name: "accounts"
  datasource:
    #url: jdbc:mysql://localhost:3306/accountsdb # These are config details for mysql
    #username: root
    #password: root
    url: jdbc:h2:mem:testdb  # In-memory database (data is lost on restart)
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # Enable H2 web console
      path: /h2-console  # Default path for H2 console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Auto-create tables
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      "qa"
  config:
    import: "optional:configserver:http://localhost:8071/" #This is the port where config server is running locally.
  cloud:
    bus:
      enabled: true #Allow application to propagate configuration changes and events across distributed microservices using a message broker like RabbitMQ or Kafka
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq: #This configures Spring Boot to connect to a RabbitMQ broker running on localhost (port 5672) using the default guest/guest credentials.
    host: localhost
    port: 5672
    username: guest
    password: guest

build:
  version: "1.0"

accounts:
  message: "This is the contact file for dev accounts env"
  info:
    name: "Piyush Rawat"
    email: "piyushkumar9818@gmail.com"
  contact:
    +917982031328
    +919650745365

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all Actuator endpoints via HTTP.
  health: # Will initialize /health/* endpoints to check the liveness and readiness of this application.
    livenessstate:
      enabled: true  # Enables the "/actuator/health/liveness" endpoint to check if the app is alive.
    readinessstate:
      enabled: true  # Enables the "/actuator/health/readiness" endpoint to check if the app is ready to receive traffic.
  endpoint:
    shutdown:
      access: unrestricted  # Allows triggering application shutdown via "/actuator/shutdown" without restrictions.
    health:
      probes:
        enabled: true  # Enables Kubernetes-style liveness & readiness probes.
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true  # Registers the service using its IP address instead of hostname.
  client:
    fetchRegistry: true  # Enables this service to fetch the registry from Eureka Server.
    registerWithEureka: true  # Allows this service to register itself with Eureka.
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/  # The Eureka Server URL where this service will register.

info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        #minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        max-wait-duration-in-half-open-state:
          seconds: 10
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
