server:
  port: 8082

spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  profiles:
    active:
      - "qa"
  config:
    import: "optional:configserver:http://localhost:8071/" #This is the port where config server is running locally.
  cloud:
    bus:
      enabled: true #Allow application to propagate configuration changes and events across distributed microservices using a message broker like RabbitMQ or Kafka
  rabbitmq: #This configures Spring Boot to connect to a RabbitMQ broker running on localhost (port 5672) using the default guest/guest credentials.
    host: localhost
    port: 5672
    username: guest
    password: guest

build:
  version: "1.0"

loans:
  message: "This is the contact file for dev accounts env"
  info:
    name: "Piyush Rawat"
    email: "piyushkumar9818@gmail.com"
  contact:
    +917982031328
    +919650745365

management:  #This enables and exposes all Spring Boot Actuator endpoints over HTTP.
  endpoints:
    web:
      exposure:
        include: "*"
