services:
  accounts:
    image: "piyushrawat147/accounts:v1"
    container_name: accounts-ms
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 900m
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network
  loans:
    image: "piyushrawat147/loans:v1"
    container_name: loans-ms
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network
  cards:
    image: "piyushrawat147/cards:v1"
    container_name: cards-ms
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network
networks:
  piyushrawat147:
    driver: "bridge" # Use the 'bridge' driver to create an isolated network for these services