services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672" #Exposes port 5672 (RabbitMQ message broker).
      - "15672:15672"`#Exposes port 15672 (RabbitMQ management UI).
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity  #Checks if RabbitMQ ports are accessible.
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
  configserver:
    image: "piyushrawat147/configserver:v2"
    container_name: configserver-ms
    ports:
      - 8071:8080
    deploy:
      resources:
        limits:
          memory: 900m
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health | grep 'UP' || exit" #Calls the Spring Boot Actuator health endpoint.
      start_interval: 10s
      timeout: 5s
      interval: 10s
      retries: 10
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network

  accounts:
    image: "piyushrawat147/accounts:v2"
    container_name: accounts-ms
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 900m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_APPLICATION_NAME: "accounts"

  cards:
    image: "piyushrawat147/cards:v2"
    container_name: cards-ms
    ports:
      - 8081:8080
    deploy:
      resources:
        limits:
          memory: 800m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_APPLICATION_NAME: "cards"

  loans:
    image: "piyushrawat147/loans:v2"
    container_name: loans-ms
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          memory: 800m
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - piyushrawat147 # Connect this service to the custom 'piyushrawat147' network
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_APPLICATION_NAME: "loans"

networks:
  piyushrawat147:
    driver: "bridge" # Use the 'bridge' driver to create an isolated network for these services